version: '3.8'

services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PORT_NUMBER=7000
    ports:
      - '7000:7000'
    networks:
      - services

  mongodb:
    container_name: mongodb
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ENABLE_IPV6=yes
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=db_root_password
      - MONGODB_USERNAME=db_user_name
      - MONGODB_PASSWORD=db_user_password
      - MONGODB_DATABASE=db_name
    networks:
      - services

networks:
  services:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.15.240.0/24
          gateway: 172.15.240.1
        - subnet: 2002:AC0F:F000::AC0F:F000/64
          gateway: 2002:AC0F:F000::AC0F:F000:1

